USE [master]
GO

/****** Object:  Database [Prueba]    Script Date: 10/04/2021 8:36:43 a. m. ******/
CREATE DATABASE [Prueba]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Prueba', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Prueba.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Prueba_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Prueba_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Prueba].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Prueba] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Prueba] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Prueba] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Prueba] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Prueba] SET ARITHABORT OFF 
GO

ALTER DATABASE [Prueba] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Prueba] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Prueba] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Prueba] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Prueba] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Prueba] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Prueba] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Prueba] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Prueba] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Prueba] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Prueba] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Prueba] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Prueba] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Prueba] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Prueba] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Prueba] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Prueba] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Prueba] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Prueba] SET  MULTI_USER 
GO

ALTER DATABASE [Prueba] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Prueba] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Prueba] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Prueba] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Prueba] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Prueba] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Prueba] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Prueba] SET  READ_WRITE 
GO


